import express from "express";
import { crearCita, obtenerTodas, obtenerPorId, actualizar, eliminar } from "../controllers/citasController.js";
import { verificarToken } from "../middlewares/authMiddleware.js";
const router=express.Router();
router.use(verificarToken);
router.post("/crear",crearCita);
router.get("/obtenerTodas",obtenerTodas);
router.get("/obtenerPorId/:id",obtenerPorId);
router.put("/actualizar/:id",actualizar);
router.delete("/delete/:id",eliminar);
export default router;
